apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink
  labels:
    app: shortlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortlink
  template:
    metadata:
      labels:
        app: shortlink
        version: "${BUILD_NUMBER}"
    spec:
      containers:
        - name: shortlink
          image: muhsyaipullah14/lnk-shortlink:${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: shortlink-svc
  labels:
    app: shortlink
spec:
  type: LoadBalancer
  selector:
    app: shortlink
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
