apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortlink
  template:
    metadata:
      labels:
        app: shortlink
        version: "${BUILD_NUMBER}"
    spec:
      containers:
      - name: shortlink
        image: muhsyaipullah14/lnk-shortlink:${BUILD_NUMBER}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shortlink-svc
spec:
  type: NodePort
  selector:
    app: shortlink
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
