apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortlink
  template:
    metadata:
      labels:
        app: shortlink
    spec:
      containers:
      - name: shortlink
        image: faritz/lnk-shortlink:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shortlink-svc
spec:
  type: NodePort
  selector:
    app: shortlink
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
